name: delfitness
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+alpha

environment:
  sdk: '>=2.18.0-42.0.dev <3.0.0'

# APP Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  formz: ^0.6.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2

  # Personal repositories
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
